version: '3.9'

services:
  database:
    container_name: mysql_db
    image: mysql:latest
    restart: always
    ports: 
      - 3306:3306
    environment:
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
    volumes:
      - db-vol:/var/lib/mysql

  app:
    build: .
    container_name: telcom-be
    restart: always
    ports: 
      - 4000:4000
    volumes: 
      - .:/usr/src/app
    depends_on:
      - database
    # command: bash -c "npx knex migrate:latest && npx knex seed:run"


volumes:
  db-vol:
    driver: local