version: '3.7'

services:

  db:
    container_name: mysql
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: '${DATABASE}'
      MYSQL_USER: '${USER}'
      MYSQL_PASSWORD: '${PASSWORD}'
      MYSQL_ROOT_PASSWORD: '${ROOT_PASSWORD}'
    ports:
      - "3306:3306"
    volumes:
      - db-vol:/var/lib/mysql
    env_file: .env

volumes:
  db-vol:
    driver: local